spring:
  profiles:
    active:
  config:
    import:
      - optional:file:.env[.properties]
      - app/authorization/authorization.yml
      - app/cors/cors.yml
      - app/oauth/oauth.yml

  flyway:
    baseline-on-migrate: true


  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SERVER_DATABASE_URI}
    username: ${SERVER_DATABASE_ROOT}
    password: ${SERVER_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none

jwt:
  secret-key: ${JWT_SECRET_KEY}
  max-age: ${JWT_MAX_AGE:3600000}

logging:
  level:
    org.springframework.web: DEBUG

server:
  port: 8080
