spring:
  flyway:
    baseline-on-migrate: true

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5442/auth
    username: root
    password: root

server:
  port: 8080
