spring:
  config:
    import:
      - optional:file:.env[.properties]
      - app/authorization/authorization-local.yml
      - app/oauth/oauth-local.yml


  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${LOCAL_DATABASE_URI}
    username: ${LOCAL_DATABASE_ROOT}
    password: ${LOCAL_DATABASE_PASSWORD}
  flyway:
    locations:
      - db/migration
   #   - db/migration/local

logging:
  level:
    org.springframework.web: debug
