spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://54.181.1.100:5432/postgres
    username: kimjaeik
    password: 1815
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none


