spring:
  profiles:
    active: local
  config:
    import:
      - app/authorization/authorization.yml
      - app/cors/cors.yml
      - app/oauth/oauth.yml

  flyway:
    baseline-on-migrate: true


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://54.181.1.100:5432/postgres
    username: kimjaeik
    password: 1815 # 1111
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none

jwt:
  secret-key: ${JWT_SECRET:yclighomeurnFinalProJectYclighomeurnFinalProJect}
  max-age: ${JWT_MAX_AGE:3600000}

logging:
  level:
    org.springframework.web: DEBUG

server:
  port: 8080
