spring:


  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5442/auth
    username: root
    password: root
  flyway:
    locations:
      - db/migration
      - db/migration/local
