spring:
  config:
    import:
      - app/authorization/authorization.yml
      - app/cors/cors.yml

  flyway:
    baseline-on-migrate: true

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5442/auth
    username: root
    password: root

jwt:
  secret-key: ${JWT_SECRET:yclighomeurnFinalProJectYclighomeurnFinalProJect}
  max-age: ${JWT_MAX_AGE:3600000}

logging:
  level:
    org.springframework.web: DEBUG

server:
  port: 8080
