demo:
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: rlawodlr302@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true  # SMTP 서버가 TLS를 사용하여 안전한 연결을 요구하는 경우 true로 설정
            required: true
          connectiontimeout: 5000 # 클라이언트가 SMTP 서버와의 연결을 설정하는 데 대기해야 하는 시간
          timeout: 5000 # 클라이언트가 SMTP 서버로부터 응답을 대기해야 하는 시간
          writetimeout: 5000 # 클라이언트가 작업 완료하는데 대기해야 하는 시간
      auth-code-expiration-millis: 18000 # 30 * 60 * 1000 == 30분 이메일 인증 코드의 만료 시간(Millisecond)